#!/sbin/busybox sh

STEP=CPU_VOLT_`echo $2`

if [ -z $3 ]; then
	evalcmd='eval echo \$$STEP'
	if [ "a`eval $evalcmd`" == "a" ]; then
		while read FREQ UVOLT; do
			eval "CPU_VOLT_$FREQ=$UVOLT"
		done < /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table
	fi
else
	eval $STEP=$3

	VOLTAGES=""
	while read FREQ UVOLT; do
		evalcmd='eval echo \$CPU_VOLT_$FREQ'
		VOLTAGES="$VOLTAGES `eval $evalcmd`"
	done < /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table

	echo $VOLTAGES > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table

fi

eval echo \$$STEP


