#!/sbin/busybox sh


if [ "a$2" != "a" ];then

	filename=$(basename $2)

	if [ "a$3" == "a" ];then
		evalcmd='eval "echo \$$filename"'
		eval $evalcmd
	else
		evalcmd='eval "$filename=$3"'
		eval $evalcmd
		evalcmd='eval "echo \$$filename"'
		eval $evalcmd

		write_values(){

			while read FREQ UVOLT; do
				cmd=`expr $UVOLT $uv_cpu`
				volt="$volt $cmd"
			done < $PROFILE_PATH/bk/bk_orig_cpu_voltage

			echo $volt > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table

		}

		case "$cpuvolt_profile" in
		  0)
		    # 0mV (Stock)
		    uv_cpu=""
		    write_values
		    ;;
		  -25)
		    # -25mV
		    uv_cpu="- 25"
		    write_values
		    ;;
		  -50)
		    # -50mV
		    uv_cpu="- 50"
		    write_values
		    ;;
		  -75)
		    # -75mV
		    uv_cpu="- 75"
		    write_values
		    ;;
		  -100)
		    # -100mV
		    uv_cpu="- 100"
		    write_values
		    ;;
		  +25)
		    # +25mV
		    uv_cpu="+ 25"
		    write_values
		    ;;
		esac;

	fi
fi
