#!/sbin/busybox sh

if [ "a$2" != "a" ];then

	filename=$(basename $2)

	if [ "a$3" == "a" ];then
	  	evalcmd='eval "echo \$$filename"'
	  	eval $evalcmd
	else
	  	evalcmd='eval "$filename=$3"'
	  	eval $evalcmd
	  	evalcmd='eval "echo \$$filename"'
	  	eval $evalcmd

		write_values()
		{
			echo $eq_values > /sys/class/misc/rem_sound/eq_gains
		}
	  
		case "$eq_profile" in

		  0)# Normal/Custom
			eq_values="0 0 0 0 0"
			write_values
		    ;; 
		  1)# Extreme Bass
			eq_values="12 8 3 -1 1"
			write_values
		    ;; 
		  2)# Bass-Treble Balance
			eq_values="10 7 0 2 5"
			write_values
		    ;;
		  3)# Treble Gain
			eq_values="-5 1 0 4 3"
			write_values	  
		    ;; 
		  4)# Classical
			eq_values="0 0 0 -3 -5"
			write_values
		    ;;
		  5)# Pleasant
			eq_values="4 3 2 2 3"
			write_values
		    ;;
		  6)# Eargasm
			eq_values="12 8 4 2 3"
			write_values
		    ;;
		  7)# LonasBeats
			eq_values="8 4 2 3 4"
			write_values
		    ;;
		  8)# BeatsBass
			eq_values="10 8 6 5 7"
			write_values
		    ;;
		  9)# Enhanced-Sound
			eq_values="9 -3 9 7 8"
			write_values
		    ;;
		  10)# DeepBass
			eq_values="10 -1 8 4 8"
			write_values
		    ;;
		  11)# Detonation
			eq_values="9 4 -2 7 11"
			write_values
		    ;;
		  12)# LonasPower
			eq_values="10 4 3 4 8"
			write_values
		    ;;
		  13)# BestCream
			eq_values="9 4 10 4 7"
			write_values
		    ;;
		esac;

	fi
fi


