#!/sbin/busybox sh

if [ -f $3 ];then
	FILEVAR=$2_$(basename $3)

	if [ -z $4 ]; then
		evalcmd='eval echo \$$FILEVAR'
		if [ "a`eval $evalcmd`" == "a" ]; then
			eval $FILEVAR=`cat $3`
		fi
	else
		echo $4 > $3

		eval $FILEVAR=`cat $3`
	fi

	eval echo \$$FILEVAR
fi
