#!/sbin/busybox sh

STEP=BUS_INT_VOLT_`echo $2`

if [ -z $3 ]; then
	evalcmd='eval echo \$$STEP'
	if [ "a`eval $evalcmd`" == "a" ]; then
		while read FREQ VOLT; do
			if [ "a`eval $evalcmd`" == "a" ]; then
				S_FREQ=`echo $FREQ | cut -c 4-`
				S_VOLT=`expr $VOLT / 1000`
				if [ ${S_FREQ} -eq $2 ]; then
					eval $STEP=$S_VOLT
					break
				fi
			fi
		done < /sys/devices/system/cpu/busfreq/int_volt_table
	fi
else
	eval $STEP=$3

	while read FREQ VOLT; do
		S_FREQ=`echo $FREQ | cut -c 4-`
		S_VOLT=`expr $3 \* 1000`
		if [ $S_FREQ -eq $2 ]; then
			echo $FREQ $S_VOLT > /sys/devices/system/cpu/busfreq/int_volt_table
		fi
	done < /sys/devices/system/cpu/busfreq/int_volt_table

fi

eval echo \$$STEP
