#!/sbin/busybox sh

if [ "a$2" != "a" ];then

	filename=$(basename $2)

	if [ "a$3" == "a" ];then
	  	evalcmd='eval "echo \$$filename"'
	  	eval $evalcmd
	else
	  	evalcmd='eval "$filename=$3"'
	  	eval $evalcmd
	  	evalcmd='eval "echo \$$filename"'
	  	eval $evalcmd

		echo `expr $lmk1 \* 256`,`expr $lmk2 \* 256`,`expr $lmk3 \* 256`,`expr $lmk4 \* 256`,`expr $lmk5 \* 256`,`expr $lmk6 \* 256` > /sys/module/lowmemorykiller/parameters/minfree

	fi
fi
