#!/sbin/busybox sh

if [[ ! -z $2 ]]; then
    filename=$(basename $2)
fi

if [[ ! -z $3 ]]; then
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
fi

mdnie_predef="0"
mdnie_find=`grep "mdnie_predef" $DEFAULT_PROFILE | cut -d'=' -f2`

write_value() {  
  echo "$1=$2" >> $DEFAULT_PROFILE
}

edit_value() {
  g_find=`grep $1=.* $DEFAULT_PROFILE`
    
  if [[ -z $g_find ]]; then
    write_value $1 $2
  else
    sed -i "s/$1=[^ ]*/$1=$2/" $DEFAULT_PROFILE 
  fi
}

write_values(){
  edit_value mdnie_preset $mdnie_preset
  edit_value mdnie_predef $mdnie_predef 

  echo $mdnie_preset >/sys/class/misc/mdnie_preset/mdnie_preset
}

case "$mdniepredef" in
  0)
    mdnie_preset="0"
    mdnie_predef="0"
    write_values
    ;;
  1)
    mdnie_preset="1"
    mdnie_predef="1"
    write_values
    ;;
 
  *)
    if [[ ! -z $mdnie_find ]]; then
      mdnie_predef="$mdnie_find"
    fi 
    ;;
esac;

eval echo $mdnie_predef
